export const THEMES = [
  {
    id: "vegas",
    name: "霓虹城",
    subtitle: "Las Vegas Hyper Bloom",
    icon: "◆",
    mood: "neon",
    accent: "#ff2bd6",
    second: "#10f1ff",
    jackpot: 888888,
    effect: "goldstorm",
    symbols: [
      { id: "wild", label: "WILD", glyph: "★", payout: [0, 0, 18, 80, 420], weight: 5 },
      { id: "seven", label: "SEVEN", glyph: "7", payout: [0, 0, 14, 70, 360], weight: 7 },
      { id: "diamond", label: "GEM", glyph: "♦", payout: [0, 0, 10, 45, 180], weight: 10 },
      { id: "bell", label: "BELL", glyph: "🔔", payout: [0, 0, 8, 32, 120], weight: 12 },
      { id: "cherry", label: "CHERRY", glyph: "🍒", payout: [0, 0, 6, 20, 80], weight: 17 },
      { id: "scatter", label: "SCATTER", glyph: "✦", payout: [0, 0, 5, 15, 60], weight: 6 },
    ],
  },
  {
    id: "egypt",
    name: "黄金埃及",
    subtitle: "Pharaoh Sun Vault",
    icon: "◈",
    mood: "sun",
    accent: "#ffd45a",
    second: "#19e0a7",
    jackpot: 999999,
    effect: "sunburst",
    symbols: [
      { id: "wild", label: "WILD", glyph: "☥", payout: [0, 0, 20, 95, 500], weight: 5 },
      { id: "mask", label: "MASK", glyph: "𓀀", payout: [0, 0, 15, 70, 320], weight: 7 },
      { id: "scarab", label: "SCARAB", glyph: "𓆣", payout: [0, 0, 10, 42, 170], weight: 11 },
      { id: "pyramid", label: "PYRAMID", glyph: "△", payout: [0, 0, 8, 34, 130], weight: 13 },
      { id: "ankh", label: "ANKH", glyph: "☀", payout: [0, 0, 6, 22, 85], weight: 16 },
      { id: "scatter", label: "SCATTER", glyph: "✦", payout: [0, 0, 5, 15, 60], weight: 6 },
    ],
  },
  {
    id: "maya",
    name: "玛雅神庙",
    subtitle: "Jade Eclipse Temple",
    icon: "✹",
    mood: "jungle",
    accent: "#24ffa8",
    second: "#ffb000",
    jackpot: 777777,
    effect: "quake",
    symbols: [
      { id: "wild", label: "WILD", glyph: "☯", payout: [0, 0, 19, 86, 440], weight: 5 },
      { id: "eclipse", label: "ECLIPSE", glyph: "◉", payout: [0, 0, 14, 64, 300], weight: 7 },
      { id: "jade", label: "JADE", glyph: "⬢", payout: [0, 0, 11, 46, 190], weight: 10 },
      { id: "serpent", label: "SERPENT", glyph: "↯", payout: [0, 0, 8, 32, 130], weight: 13 },
      { id: "totem", label: "TOTEM", glyph: "▣", payout: [0, 0, 6, 20, 80], weight: 16 },
      { id: "scatter", label: "SCATTER", glyph: "✦", payout: [0, 0, 5, 15, 60], weight: 6 },
    ],
  },
  {
    id: "arctic",
    name: "极光冰原",
    subtitle: "Aurora Frost Rush",
    icon: "✧",
    mood: "frost",
    accent: "#86f8ff",
    second: "#b28cff",
    jackpot: 666666,
    effect: "blizzard",
    symbols: [
      { id: "wild", label: "WILD", glyph: "❄", payout: [0, 0, 18, 82, 410], weight: 5 },
      { id: "aurora", label: "AURORA", glyph: "⌁", payout: [0, 0, 13, 62, 280], weight: 8 },
      { id: "crystal", label: "CRYSTAL", glyph: "◇", payout: [0, 0, 10, 44, 175], weight: 10 },
      { id: "moon", label: "MOON", glyph: "☾", payout: [0, 0, 8, 30, 120], weight: 13 },
      { id: "flake", label: "FLAKE", glyph: "✻", payout: [0, 0, 6, 20, 75], weight: 17 },
      { id: "scatter", label: "SCATTER", glyph: "✦", payout: [0, 0, 5, 15, 60], weight: 6 },
    ],
  },
  {
    id: "dragon",
    name: "龙焰工坊",
    subtitle: "Dragon Forge Inferno",
    icon: "♨",
    mood: "ember",
    accent: "#ff5a1f",
    second: "#ffd05a",
    jackpot: 1234567,
    effect: "inferno",
    symbols: [
      { id: "wild", label: "WILD", glyph: "龍", payout: [0, 0, 24, 110, 620], weight: 4 },
      { id: "crown", label: "CROWN", glyph: "♛", payout: [0, 0, 16, 76, 360], weight: 7 },
      { id: "forge", label: "FORGE", glyph: "⬣", payout: [0, 0, 12, 50, 220], weight: 10 },
      { id: "flame", label: "FLAME", glyph: "🔥", payout: [0, 0, 9, 36, 150], weight: 12 },
      { id: "coin", label: "COIN", glyph: "●", payout: [0, 0, 6, 22, 85], weight: 17 },
      { id: "scatter", label: "SCATTER", glyph: "✦", payout: [0, 0, 5, 15, 60], weight: 6 },
    ],
  },
];

export const PAYLINES = [
  [1, 1, 1, 1, 1],
  [0, 0, 0, 0, 0],
  [2, 2, 2, 2, 2],
  [0, 1, 2, 1, 0],
  [2, 1, 0, 1, 2],
];

export const BET_STEPS = [20, 50, 100, 200, 500, 1000, 2000, 5000];
